"""
Django settings for nutriaDB project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('NUTRIA_SECRET_KEY', '_8@=tgd$&8x%818&@_d1s-lo)afmx18nl$#tny!#=-=zc$smm=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('NUTRIA_DEBUG_MODE', 'True') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'backend.apps.BackendConfig',
    'jsonAPI.apps.JsonapiConfig',
    'binaryAPI.apps.BinaryapiConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'nutriaDB.middleware.CorsHeaderMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nutriaDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nutriaDB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('NUTRIA_DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('NUTRIA_DB_NAME', os.path.join(BASE_DIR, 'db.sqlite3')),
    }
}
e = os.getenv('NUTRIA_DB_USER')
if e:
    DATABASES['default']['USER'] = e
e = os.getenv('NUTRIA_DB_PASSWORD')
if e:
    DATABASES['default']['PASSWORD'] = e
e = os.getenv('NUTRIA_DB_HOST')
if e:
    DATABASES['default']['HOST'] = e
e = os.getenv('NUTRIA_DB_PORT')
if e:
    DATABASES['default']['PORT'] = e


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = os.getenv('NUTRIA_LANGUAGE_CODE', 'de-de')

TIME_ZONE = os.getenv('NUTRIA_TIME_ZONE', 'Europe/Berlin')

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/var/www/static'

JWT_SECRET = os.getenv('NUTRIA_JWT_SECRET', 'SrFbE63DV7xy0R01')
