# Generated by Django 2.1.3 on 2019-01-11 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Usually 'piece', 'slice', 'teaspoon', 'large glass' or 'handful'.", max_length=256)),
                ('size', models.FloatField(help_text='Size of the serving in g')),
                ('food_is_recipe', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='backend.Recipe')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='backend.Product')),
            ],
        ),
    ]
